title: <p align="center"> Sanika Mahabaleshwarkar </p>
logo: assets/img/IMG_2169.jpg

description:
  <p align="center">
  <a href="Harshitha_Kolipaka_Salesforce_CV_April_25.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mkarsanika/">LinkedIn</a> |
  <a href="https://github.com/mkarsanika">GitHub</a>
  
  </p>



theme: jekyll-theme-minimal
