title: <p align="center"> Sanika Mahabaleshwarkar </p>
logo: assets/img/Sanika_M_Photo.jpeg

description:
  <p align="center">
  <a href="/docs/Sanika_Mahabaleshwarkar_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mkarsanika/">LinkedIn</a> |
  <a href="https://github.com/mkarsanika">GitHub</a>
  
  </p>



theme: jekyll-theme-minimal
