title: <p align="center"> Harshitha Kolipaka </p>
logo: assets/img/IMG_2169.jpg

description:
  <p align="center">
  <a href="Harshitha_Kolipaka_Salesforce_CV_April_25.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/harshitha-kolipaka-06b7411aa/">LinkedIn</a> |
  <a href="https://github.com/harshithakolipaka28">GitHub</a>
  
  </p>



theme: jekyll-theme-minimal
